/* js/lookups.js 
 here are all the NM county and city code tables */

const COUNTIES = [
  {code:1, name:'Bernalillo'},
  {code:2, name:'Catron'},
  {code:3, name:'Chaves'},
  {code:4, name:'Cibola'},
  {code:5, name:'Colfax'},
  {code:6, name:'Curry'},
  {code:7, name:'De Baca'},
  {code:8, name:'Doña Ana'},
  {code:9, name:'Eddy'},
  {code:10, name:'Grant'},
  {code:11, name:'Guadalupe'},
  {code:12, name:'Harding'},
  {code:13, name:'Hidalgo'},
  {code:14, name:'Lea'},
  {code:15, name:'Lincoln'},
  {code:16, name:'Los Alamos'},
  {code:17, name:'Luna'},
  {code:18, name:'McKinley'},
  {code:19, name:'Mora'},
  {code:20, name:'Otero'},
  {code:21, name:'Quay'},
  {code:22, name:'Rio Arriba'},
  {code:23, name:'Roosevelt'},
  {code:24, name:'Sandoval'},
  {code:25, name:'San Juan'},
  {code:26, name:'San Miguel'},
  {code:27, name:'Santa Fe'},
  {code:28, name:'Sierra'},
  {code:29, name:'Socorro'},
  {code:30, name:'Taos'},
  {code:31, name:'Torrance'},
  {code:32, name:'Union'},
  {code:33, name:'Valencia'},
];

const CITIES = [
  {code:1, name:'Abeytas'},
  {code:2, name:'Abo'},
  {code:3, name:'Abiquiu'},
  {code:4, name:'Acoma'},
  {code:5, name:'Acomita'},
  {code:6, name:'Abiquiu Lake'},
  {code:7, name:'Agua Fria'},
  {code:8, name:'Acomita Lake'},
  {code:9, name:'Adelino'},
  {code:10, name:'Alameda'},
  {code:16, name:'Alamillo'},
  {code:20, name:'Alamogordo'},
  {code:21, name:'Angel Fire'},
  {code:22, name:'Alamo Navajo'},
  {code:25, name:'Anzac Village'},
  {code:26, name:'Allison'},
  {code:27, name:'Anapra'},
  {code:28, name:'Alto'},
  {code:29, name:'Algodones'},
  {code:30, name:'Albuquerque'},
  {code:31, name:'Alcalde'},
  {code:32, name:'Amalia'},
  {code:33, name:'Animas'},
  {code:34, name:'Anthony'},
  {code:35, name:'Ambrosia Lake'},
  {code:36, name:'Amistad'},
  {code:37, name:'Anton Chico'},
  {code:38, name:'Apache Creek'},
  {code:39, name:'Ancho'},
  {code:40, name:'Armijo'},
  {code:41, name:'Aragon'},
  {code:42, name:'Antelope Wells'},
  {code:43, name:'Arenas Valley'},
  {code:44, name:'Arroyo del Pueblo'},
  {code:45, name:'Arrey'},
  {code:46, name:'Arroyo Seco'},
  {code:47, name:'Arroyo Hondo'},
  {code:48, name:'Anthony Town'},
  {code:49, name:'Arboles'},
  {code:50, name:'Artesia'},
  {code:55, name:'Atoka'},
  {code:60, name:'Atrisco'},
  {code:70, name:'Aztec'},
  {code:75, name:'Bard'},
  {code:90, name:'Bayard'},
  {code:94, name:'Brazito'},
  {code:95, name:'Budville'},
  {code:96, name:'Beclabito'},
  {code:97, name:'Bibo'},
  {code:99, name:'None'},
  {code:100, name:'Belen'},
  {code:101, name:'Bosque Farms'},
  {code:102, name:'Black Rock'},
  {code:103, name:'Bellview'},
  {code:104, name:'Bent'},
  {code:105, name:'Buckeye'},
  {code:106, name:'Buckhorn'},
  {code:107, name:'Brazos'},
  {code:108, name:'Berino'},
  {code:109, name:'Bingham'},
  {code:110, name:'Bernalillo'},
  {code:111, name:'Broadview'},
  {code:112, name:'Bueyeros'},
  {code:113, name:'Bosque'},
  {code:114, name:'Blanco'},
  {code:115, name:'Bloomfield'},
  {code:116, name:'Bluewater Village'},
  {code:117, name:'Brimhall Nizhoni'},
  {code:118, name:'Canjilon'},
  {code:119, name:'Cañoncito'},
  {code:120, name:'Capitan'},
  {code:121, name:'Cannon AFB'},
  {code:122, name:'Caballo'},
  {code:123, name:'Caprock'},
  {code:124, name:'Buena Vista'},
  {code:125, name:'Capulin'},
  {code:126, name:'Cañones'},
  {code:127, name:'Casa Blanca'},
  {code:128, name:'Canon Plaza'},
  {code:129, name:'Cannon'},
  {code:130, name:'Carlsbad'},
  {code:131, name:'Cañada de los Alamos'},
  {code:132, name:'Cañon'},
  {code:133, name:'Boles Acres'},
  {code:134, name:'Canova'},
  {code:135, name:'Canutillo'},
  {code:136, name:'Carnuel'},
  {code:139, name:'Casa Colorada'},
  {code:140, name:'Carrizozo'},
  {code:141, name:'Carson'},
  {code:142, name:'Causey'},
  {code:143, name:'Cebolla'},
  {code:144, name:'Cedarvale'},
  {code:145, name:'Cedar Grove'},
  {code:146, name:'Cedar Hill'},
  {code:148, name:'Cedar Crest'},
  {code:149, name:'Cedro'},
  {code:150, name:'Santa Clara'},
  {code:151, name:'Cerrillos'},
  {code:152, name:'Cerro'},
  {code:153, name:'Chacon'},
  {code:154, name:'Chaparral'},
  {code:155, name:'Chama'},
  {code:156, name:'Chamisal'},
  {code:157, name:'Chamberino'},
  {code:158, name:'Chimayo'},
  {code:159, name:'Church Rock'},
  {code:160, name:'Cimarron'},
  {code:161, name:'Chilili'},
  {code:162, name:'Chamita'},
  {code:163, name:'Chamizal'},
  {code:164, name:'Chical'},
  {code:165, name:'Chili'},
  {code:166, name:'Chupadero'},
  {code:170, name:'Clayton'},
  {code:171, name:'Claunch'},
  {code:173, name:'Cleveland'},
  {code:175, name:'Cliff'},
  {code:177, name:'Clines Corners'},
  {code:180, name:'Cloudcroft'},
  {code:190, name:'Clovis'},
  {code:193, name:'Cobre'},
  {code:195, name:'Cochiti'},
  {code:196, name:'Cochiti Lake'},
  {code:200, name:'Columbus'},
  {code:203, name:'Conchas Dam'},
  {code:205, name:'Continental Divide'},
  {code:206, name:'Cotton City'},
  {code:207, name:'Cordova'},
  {code:208, name:'Corrales'},
  {code:209, name:'Crossroads'},
  {code:210, name:'Corona'},
  {code:211, name:'Costilla'},
  {code:212, name:'Counselor'},
  {code:213, name:'Coyote'},
  {code:214, name:'Crystal'},
  {code:215, name:'Crownpoint'},
  {code:216, name:'Cuba'},
  {code:217, name:'Cubero'},
  {code:218, name:'Cuchillo'},
  {code:219, name:'Datil'},
  {code:220, name:'Cowles'},
  {code:221, name:'Cuervo'},
  {code:222, name:'Cruzville'},
  {code:223, name:'Cuartelez'},
  {code:224, name:'Cundiyo'},
  {code:225, name:'Cuyamungue Grant'},
  {code:226, name:'Cuyamungue'},
  {code:230, name:'Deming'},
  {code:235, name:'Derry'},
  {code:237, name:'Dog Canyon'},
  {code:239, name:'Domingo'},
  {code:240, name:'Des Moines'},
  {code:249, name:'Doña Ana Range Camp'},
  {code:250, name:'Dexter'},
  {code:251, name:'Dixon'},
  {code:252, name:'Dora'},
  {code:253, name:'Doña Ana'},
  {code:254, name:'Dusty'},
  {code:255, name:'Dulce'},
  {code:256, name:'Duran'},
  {code:257, name:'Eagle Nest'},
  {code:258, name:'Elephant Butte'},
  {code:259, name:'East Pecos'},
  {code:260, name:'Elida'},
  {code:261, name:'Edgewood'},
  {code:262, name:'Elkins'},
  {code:263, name:'El Cerro Mission'},
  {code:264, name:'El Duende'},
  {code:265, name:'El Paso'},
  {code:266, name:'El Rito'},
  {code:267, name:'El Vado'},
  {code:268, name:'El Prado'},
  {code:269, name:'Encinal'},
  {code:270, name:'Encino'},
  {code:271, name:'El Rancho'},
  {code:272, name:'Embudo'},
  {code:273, name:'Escabosa'},
  {code:274, name:'Ensenada'},
  {code:275, name:'Escondida'},
  {code:276, name:'El Valle de Arroyo Seco'},
  {code:277, name:'Eldorado at Santa Fe'},
  {code:278, name:'Edith Endave'},
  {code:279, name:'El Cerro'},
  {code:280, name:'Española'},
  {code:281, name:'Escudilla Bonita'},
  {code:290, name:'Estancia'},
  {code:300, name:'Eunice'},
  {code:303, name:'Fairacres'},
  {code:305, name:'Farley'},
  {code:310, name:'Farmington'},
  {code:311, name:'Faywood'},
  {code:312, name:'Fence Lake'},
  {code:313, name:'Fierro'},
  {code:317, name:'Flying H'},
  {code:318, name:'Floyd'},
  {code:319, name:'Flora Vista'},
  {code:320, name:'Folsom'},
  {code:321, name:'Forrest'},
  {code:322, name:'Fort Bayard'},
  {code:324, name:'Fort Defiance'},
  {code:325, name:'Fort Stanton'},
  {code:330, name:'Fort Sumner'},
  {code:332, name:'Fort Wingate'},
  {code:335, name:'Fruitland'},
  {code:336, name:'Gabaldon'},
  {code:337, name:'Garita'},
  {code:338, name:'Glencoe'},
  {code:339, name:'Gallina'},
  {code:340, name:'Gallup'},
  {code:341, name:'Gila'},
  {code:342, name:'Garfield'},
  {code:343, name:'Glenwood'},
  {code:344, name:'Golden'},
  {code:345, name:'Galisteo'},
  {code:346, name:'Gamerco'},
  {code:347, name:'Gallinas'},
  {code:348, name:'Gladstone'},
  {code:349, name:'Glenrio'},
  {code:350, name:'Grady'},
  {code:351, name:'Glorieta'},
  {code:352, name:'Glen Acres'},
  {code:353, name:'Gila Hot Springs'},
  {code:354, name:'Gonzales Ranch'},
  {code:360, name:'Grants'},
  {code:365, name:'Greenfield'},
  {code:380, name:'Grenville'},
  {code:381, name:'Guadalupita'},
  {code:389, name:'Hachita'},
  {code:390, name:'Hagerman'},
  {code:395, name:'Hanover'},
  {code:397, name:'Happy Valley'},
  {code:400, name:'Hatch'},
  {code:405, name:'Hayden'},
  {code:406, name:'Hernandez'},
  {code:407, name:'Highland Meadows'},
  {code:408, name:'High Rolls Mt Park'},
  {code:409, name:'Hillsboro'},
  {code:410, name:'Hobbs'},
  {code:415, name:'Holloman AFB'},
  {code:416, name:'Homestead'},
  {code:417, name:'Hondo'},
  {code:418, name:'Holman'},
  {code:420, name:'Hope'},
  {code:421, name:'House'},
  {code:422, name:'Horse Springs'},
  {code:423, name:'Humble City'},
  {code:424, name:'Hot Springs Landing'},
  {code:430, name:'Hurley'},
  {code:433, name:'Indian Hills'},
  {code:435, name:'Isleta Pueblo'},
  {code:437, name:'Jacona'},
  {code:438, name:'Jaconita'},
  {code:440, name:'Jal'},
  {code:442, name:'Jicarilla Apache'},
  {code:446, name:'La Huerta'},
  {code:447, name:'Keeler Farm'},
  {code:448, name:'La Cueva'},
  {code:449, name:'La Hacienda'},
  {code:450, name:'Jarales'},
  {code:451, name:'Jemez Springs'},
  {code:452, name:'Jemez Pueblo'},
  {code:453, name:'Kenna'},
  {code:454, name:'Kingston'},
  {code:455, name:'Kirtland AFB'},
  {code:456, name:'Kirtland'},
  {code:457, name:'Laguna'},
  {code:458, name:'La Jara'},
  {code:459, name:'Lakewood'},
  {code:460, name:'Lake Arthur'},
  {code:461, name:'La Joya'},
  {code:462, name:'La Luz'},
  {code:463, name:'La Loma'},
  {code:464, name:'La Madera'},
  {code:465, name:'La Mesa'},
  {code:466, name:'La Plata'},
  {code:467, name:'La Cienega'},
  {code:468, name:'Lamy'},
  {code:469, name:'La Puente'},
  {code:470, name:'Las Cruces'},
  {code:471, name:'La Mesilla'},
  {code:472, name:'Las Maravillas'},
  {code:473, name:'Las Nutrias'},
  {code:474, name:'Las Palomas'},
  {code:475, name:'Las Tablas'},
  {code:476, name:'La Puebla'},
  {code:477, name:'La Villita'},
  {code:478, name:'Lake Roberts'},
  {code:479, name:'Lake Roberts Heights'},
  {code:480, name:'Las Vegas'},
  {code:481, name:'Lake Valley'},
  {code:486, name:'Lee Acres'},
  {code:487, name:'Lake Sumner'},
  {code:488, name:'Leyba'},
  {code:489, name:'Lindrith'},
  {code:491, name:'Ledoux'},
  {code:492, name:'La Union'},
  {code:493, name:'Lemitar'},
  {code:494, name:'Lingo'},
  {code:495, name:'Lincoln'},
  {code:497, name:'Loco Hills'},
  {code:498, name:'Llaves'},
  {code:499, name:'Logan'},
  {code:500, name:'Lordsburg'},
  {code:501, name:'Llano'},
  {code:502, name:'Livingston Wheeler'},
  {code:503, name:'Llano del Medio'},
  {code:504, name:'Llano Quemado'},
  {code:510, name:'Los Alamos'},
  {code:515, name:'Los Cerrillos'},
  {code:520, name:'Los Chaves'},
  {code:522, name:'Los Colonias'},
  {code:525, name:'Los Luceros'},
  {code:530, name:'Los Lunas'},
  {code:534, name:'Los Ojos'},
  {code:536, name:'Los Padillas'},
  {code:537, name:'Los Ranchos de Albuquerque'},
  {code:540, name:'Loving'},
  {code:548, name:'Luis Lopez'},
  {code:549, name:'Lower Frisco'},
  {code:550, name:'Lovington'},
  {code:551, name:'Luna'},
  {code:552, name:'Lumberton'},
  {code:553, name:'McDonald'},
  {code:554, name:'Lupton'},
  {code:555, name:'McAlister'},
  {code:556, name:'Lyden'},
  {code:557, name:'McGaffey'},
  {code:558, name:'McCartys Village'},
  {code:559, name:'McIntosh'},
  {code:560, name:'Magdalena'},
  {code:561, name:'Madrid'},
  {code:562, name:'Manzano Springs'},
  {code:563, name:'Madrone'},
  {code:565, name:'Malaga'},
  {code:566, name:'Manuelito'},
  {code:567, name:'Maljamar'},
  {code:568, name:'Manzano'},
  {code:570, name:'Maxwell'},
  {code:571, name:'Nadine'},
  {code:572, name:'Nakaibito'},
  {code:573, name:'Nenahnezad'},
  {code:574, name:'Moquino'},
  {code:575, name:'Mayhill'},
  {code:576, name:'Meadow Lake'},
  {code:577, name:'Medanales'},
  {code:578, name:'Oasis'},
  {code:579, name:'Ojo Amarillo'},
  {code:580, name:'Melrose'},
  {code:581, name:'Middle Frisco'},
  {code:582, name:'Mountain View'},
  {code:583, name:'Mentmore'},
  {code:584, name:'Miami'},
  {code:585, name:'Mescalero Apache'},
  {code:586, name:'Mills'},
  {code:587, name:'Milnesand'},
  {code:588, name:'Mogollon'},
  {code:589, name:'Monticello'},
  {code:590, name:'Mesilla'},
  {code:591, name:'Monterey Park'},
  {code:592, name:'Mesilla Park'},
  {code:593, name:'Midway'},
  {code:594, name:'Mesita'},
  {code:595, name:'Monero'},
  {code:596, name:'Mesquite'},
  {code:597, name:'Mexican Springs'},
  {code:598, name:'Milan'},
  {code:599, name:'Mimbres'},
  {code:600, name:'Mosquero'},
  {code:601, name:'Montezuma'},
  {code:602, name:'Monument'},
  {code:603, name:'Montoya'},
  {code:604, name:'Mora'},
  {code:605, name:'Moriarty'},
  {code:606, name:'Mount Dora'},
  {code:607, name:'New Laguna'},
  {code:608, name:'Ocate'},
  {code:609, name:'Mule Creek'},
  {code:610, name:'Mountainair'},
  {code:611, name:'Nambe Pueblo'},
  {code:612, name:'Navajo'},
  {code:613, name:'Nageezi'},
  {code:614, name:'Nara Visa'},
  {code:615, name:'Navajo Dam'},
  {code:616, name:'Newkirk'},
  {code:617, name:'Naschitti'},
  {code:618, name:'Ojo Feliz'},
  {code:619, name:'Nogal'},
  {code:620, name:'Ohkay Owingeh'},
  {code:621, name:'Pinos Altos'},
  {code:622, name:'Oil Center'},
  {code:623, name:'Ojo Caliente'},
  {code:624, name:'Organ'},
  {code:625, name:'Orogrande'},
  {code:626, name:'Newcomb'},
  {code:627, name:'Otis'},
  {code:628, name:'Paguate'},
  {code:629, name:'Park View'},
  {code:630, name:'Pecos'},
  {code:631, name:'Pilar'},
  {code:632, name:'Placitas'},
  {code:633, name:'Peña Blanca'},
  {code:634, name:'Peñasco'},
  {code:635, name:'Peralta'},
  {code:636, name:'Pie Town'},
  {code:637, name:'Picuris Pueblo'},
  {code:638, name:'Pinedale'},
  {code:639, name:'Pojoaque'},
  {code:640, name:'Portales'},
  {code:641, name:'Placita'},
  {code:642, name:'Prewitt'},
  {code:643, name:'Puerto de Luna'},
  {code:644, name:'Quemado'},
  {code:645, name:'Questa'},
  {code:646, name:'Ramah'},
  {code:647, name:'Petaca'},
  {code:648, name:'Ponderosa'},
  {code:649, name:'Radium Springs'},
  {code:650, name:'Ranchos de Taos'},
  {code:651, name:'Pep'},
  {code:652, name:'Picacho'},
  {code:653, name:'Piñon'},
  {code:654, name:'Polvadera'},
  {code:655, name:'Quay'},
  {code:656, name:'Rainsville'},
  {code:657, name:'Rencona'},
  {code:658, name:'Ribera'},
  {code:659, name:'Rociada'},
  {code:660, name:'Raton'},
  {code:661, name:'Ojo Sarco'},
  {code:662, name:'Reserve'},
  {code:663, name:'Rincon'},
  {code:664, name:'Red River'},
  {code:665, name:'Playas'},
  {code:666, name:'Rodarte'},
  {code:667, name:'Rodeo'},
  {code:668, name:'Rehoboth'},
  {code:669, name:'Salem'},
  {code:670, name:'Roswell'},
  {code:671, name:'Pinehill'},
  {code:672, name:'Regina'},
  {code:673, name:'Punta de Agua'},
  {code:674, name:'Redrock'},
  {code:675, name:'Rogers'},
  {code:676, name:'Rinconado'},
  {code:677, name:'Rio Rancho'},
  {code:678, name:'Rowe'},
  {code:679, name:'Riverside'},
  {code:680, name:'Roy'},
  {code:681, name:'Sabinoso'},
  {code:682, name:'Romero'},
  {code:683, name:'Paraje'},
  {code:684, name:'Pastura'},
  {code:685, name:'Peak Place'},
  {code:686, name:'Sandia Knolls'},
  {code:687, name:'Rosedale'},
  {code:689, name:'San Cristobal'},
  {code:690, name:'Ruidoso'},
  {code:691, name:'Ruidoso Downs'},
  {code:692, name:'Rutheron'},
  {code:693, name:'Saint Vrain'},
  {code:694, name:'Sapello'},
  {code:695, name:'Sacramento'},
  {code:696, name:'Sandia Park'},
  {code:697, name:'Pueblo of Sandia'},
  {code:698, name:'San Antonio'},
  {code:699, name:'San Acacia'},
  {code:700, name:'San Jon'},
  {code:701, name:'Sandia Base Mil Resv'},
  {code:702, name:'San Fidel'},
  {code:703, name:'Ohkay Owingeh'},
  {code:704, name:'San Rafael'},
  {code:705, name:'Pueblo Pintado'},
  {code:706, name:'Santa Ana Pueblo'},
  {code:707, name:'Santa Clara Pueblo'},
  {code:708, name:'Santa Clara'},
  {code:709, name:'Santa Cruz'},
  {code:710, name:'Santa Fe'},
  {code:711, name:'San Felipe Pueblo'},
  {code:712, name:'San Ildefonso Pueblo'},
  {code:713, name:'Ponderosa Pine'},
  {code:714, name:'Sanostee'},
  {code:715, name:'Pleasanton'},
  {code:716, name:'San Patricio'},
  {code:717, name:'San Jose'},
  {code:718, name:'San Mateo'},
  {code:719, name:'San Miguel'},
  {code:720, name:'Santa Rita'},
  {code:721, name:'Serafina'},
  {code:722, name:'San Francisco Plaza'},
  {code:723, name:'San Lorenzo'},
  {code:724, name:'Placitas (Doña Ana)'},
  {code:725, name:'Scholle'},
  {code:726, name:'Pueblitos'},
  {code:727, name:'Pueblo of Sandia Village'},
  {code:728, name:'Ranchito'},
  {code:729, name:'San Pablo'},
  {code:730, name:'Santa Rosa'},
  {code:731, name:'Red Hill'},
  {code:732, name:'Rio Communities'},
  {code:733, name:'Rio en Medio'},
  {code:734, name:'Rio Lucio'},
  {code:735, name:'Santa Teresa'},
  {code:736, name:'Road Forks'},
  {code:737, name:'Rock Springs'},
  {code:738, name:'San Ysidro (Doña Ana)'},
  {code:739, name:'Sandia Heights'},
  {code:740, name:'Santo Domingo Pueblo'},
  {code:741, name:'Sausal'},
  {code:742, name:'San Ysidro'},
  {code:743, name:'Seama'},
  {code:744, name:'Shady Brook'},
  {code:745, name:'Shiprock'},
  {code:746, name:'Seneca'},
  {code:747, name:'Seboyeta'},
  {code:748, name:'Sedan'},
  {code:749, name:'Sena'},
  {code:750, name:'Silver City'},
  {code:754, name:'Skyline-Ganipa'},
  {code:755, name:'San Antonito'},
  {code:756, name:'San Antonito (Socorro)'},
  {code:757, name:'San Jose (San Miguel)'},
  {code:758, name:'San Luis'},
  {code:759, name:'San Pedro'},
  {code:760, name:'Socorro'},
  {code:761, name:'South Acomita Village'},
  {code:762, name:'South Valley'},
  {code:763, name:'Sedillo'},
  {code:764, name:'Sheep Springs'},
  {code:765, name:'Soham'},
  {code:766, name:'Solano'},
  {code:767, name:'Sombrillo'},
  {code:768, name:'Spencer Valley'},
  {code:769, name:'Spencerville'},
  {code:770, name:'Springer'},
  {code:771, name:'Sunshine'},
  {code:772, name:'Sunspot'},
  {code:773, name:'Standing Rock'},
  {code:774, name:'Stanley'},
  {code:775, name:'Sunland Park'},
  {code:776, name:'Stead'},
  {code:777, name:'Taos Pueblo'},
  {code:778, name:'Taiban'},
  {code:779, name:'Tajique'},
  {code:780, name:'Taos'},
  {code:781, name:'Talpa'},
  {code:782, name:'Tolar'},
  {code:783, name:'Taos Ski Valley'},
  {code:788, name:'Teec Nos Pos'},
  {code:789, name:'Tecolote'},
  {code:790, name:'Tatum'},
  {code:791, name:'Tecolotito'},
  {code:792, name:'Tererro'},
  {code:795, name:'Tesuque'},
  {code:796, name:'Tesuque Pueblo'},
  {code:799, name:'Trout Valley'},
  {code:800, name:'Texico'},
  {code:802, name:'Timberon'},
  {code:803, name:'Tinnie'},
  {code:804, name:'Thoreau'},
  {code:805, name:'Tierra Amarilla'},
  {code:806, name:'Tijeras'},
  {code:807, name:'Tohatchi'},
  {code:808, name:'Three Rivers'},
  {code:809, name:'Tres Piedras'},
  {code:810, name:'Truth or Consequences'},
  {code:811, name:'Toadlena'},
  {code:812, name:'Truchas'},
  {code:813, name:'Tome'},
  {code:814, name:'Trampas'},
  {code:815, name:'Trementina'},
  {code:816, name:'Trujillo'},
  {code:817, name:'Turnerville'},
  {code:818, name:'Tyrone'},
  {code:819, name:'Tres Ritos'},
  {code:820, name:'Tucumcari'},
  {code:821, name:'Torreon'},
  {code:822, name:'Torreon (Torrance)'},
  {code:823, name:'Tse Bonito'},
  {code:824, name:'Twin Forks'},
  {code:825, name:'Twin Lakes'},
  {code:830, name:'Tularosa'},
  {code:832, name:'Valencia'},
  {code:833, name:'Ute Park'},
  {code:834, name:'Upper Fruitland'},
  {code:835, name:'University Park'},
  {code:836, name:'Vallecitos'},
  {code:837, name:'Vado'},
  {code:838, name:'Vadito'},
  {code:839, name:'Valmora'},
  {code:840, name:'Vaughn'},
  {code:841, name:'Valdez'},
  {code:842, name:'Vanderwagen'},
  {code:843, name:'Van Wagen'},
  {code:844, name:'Ventura'},
  {code:845, name:'Velarde'},
  {code:846, name:'Veguita'},
  {code:847, name:'Vermejo Park'},
  {code:848, name:'Vanadium'},
  {code:849, name:'Villanueva'},
  {code:850, name:'Virden'},
  {code:860, name:'Wagon Mound'},
  {code:863, name:'White Signal'},
  {code:864, name:'Weed'},
  {code:865, name:'Walker AFB'},
  {code:866, name:'West Hammond'},
  {code:867, name:'Waterflow'},
  {code:868, name:'Watrous'},
  {code:869, name:'Whites City'},
  {code:870, name:'Willard'},
  {code:871, name:'White Sands Msl Rge'},
  {code:872, name:'Williamsburg'},
  {code:873, name:'Winston'},
  {code:874, name:'White Rock'},
  {code:875, name:'Yah-ta-hey'},
  {code:876, name:'Yeso'},
  {code:877, name:'Youngsville'},
  {code:879, name:'Zia Pueblo'},
  {code:880, name:'Zuni Pueblo'},
  {code:881, name:'Windmill'},
  {code:882, name:'Window Rock'},
  {code:883, name:'Pulpotio Bareas'},
  {code:884, name:'Tohajiilee'},
  {code:885, name:'Young Place'},
  {code:886, name:'North San Ysidro (San Miguel)'},
  {code:897, name:'City of the Sun'},
  {code:917, name:'Morningside'},
  {code:918, name:'Napi Headquarters'},
  {code:919, name:'North Acomita Village'},
  {code:920, name:'North Hobbs'},
  {code:921, name:'North Hurley'},
  {code:922, name:'North Light Plant'},
  {code:923, name:'North Valley'},
  {code:924, name:'Pajarito Mesa'},
  {code:925, name:'Paradise Hills'},
  {code:926, name:'Pecan Park'},
  {code:927, name:'Pueblito'},
  {code:928, name:'Pueblo'},
  {code:929, name:'Rancho Grande'},
  {code:930, name:'Rivers'},
  {code:931, name:'Rodey'},
  {code:932, name:'Alma'},
  {code:933, name:'Angustura'},
  {code:934, name:'Barton'},
  {code:935, name:'Becenti'},
  {code:936, name:'Black Hat'},
  {code:937, name:'Borrego Pass'},
  {code:938, name:'Butterfield Park'},
  {code:939, name:'Candy Kitchen'},
  {code:940, name:'Casas Adobes'},
  {code:941, name:'Catalpa Canyon'},
  {code:942, name:'Center Point'},
  {code:943, name:'Conejo'},
  {code:944, name:'Crestview'},
  {code:945, name:'Crouch Mesa'},
  {code:946, name:'Deer Canyon'},
  {code:947, name:'El Morro Valley'},
  {code:948, name:'Encantado'},
  {code:949, name:'Golden Acres'},
  {code:950, name:'Haystack'},
  {code:951, name:'Homer C Jones'},
  {code:952, name:'Hyde Park'},
  {code:953, name:'Iyanbito'},
  {code:954, name:'Jamestown'},
  {code:955, name:'La Bajada'},
  {code:956, name:'La Boca'},
  {code:957, name:'La Tierra'},
  {code:958, name:'Las Campanas'},
  {code:959, name:'Las Tusas'},
  {code:960, name:'Little Walnut Village'},
  {code:961, name:'Lobo Canyon'},
  {code:962, name:'Lybrook'},
  {code:963, name:'Middle Mesa'},
  {code:964, name:'Mount Taylor'},
  {code:965, name:'Ojo Encino'},
  {code:966, name:'Old Town (Luna)'},
  {code:967, name:'Paa-Ko'},
  {code:968, name:'Pinehaven'},
  {code:969, name:'Purty Rock'},
  {code:970, name:'Red Rock Ranch'},
  {code:971, name:'Rio Chiquito'},
  {code:972, name:'Rio Rancho Estates'},
  {code:973, name:'Sagar'},
  {code:974, name:'Santa Fe Foothills'},
  {code:975, name:'Seton Village'},
  {code:976, name:'South River'},
  {code:977, name:'Stoneridge'},
  {code:978, name:'Sundance'},
  {code:979, name:'Sunlit Hills'},
  {code:980, name:'Tano Road'},
  {code:981, name:'Thunder Mountain'},
  {code:982, name:'Timberlake'},
  {code:983, name:'Tortugas'},
  {code:984, name:'Totah Vista'},
  {code:985, name:'Tres Arroyos'},
  {code:986, name:'Turley'},
  {code:987, name:'Valle Vista'},
  {code:988, name:'White Cliffs'},
  {code:989, name:'White Sands'},
  {code:990, name:'Williams Acres'},
  {code:991, name:'Arroyo Hondo (Santa Fe)'},
  {code:992, name:'Bluewater (McKinley)'},
  {code:993, name:'La Cueva (Santa Fe)'},
  {code:994, name:'La Madera (Sandoval)'},
  {code:995, name:'Mountain View (Cibola)'},
  {code:996, name:'Valencia (Santa Fe)'},
];